const estato = [
  { id: 'AC', estado: 'Acre', Captal: 'Rio Branco' },
  { id: 'AL', estado: 'Alagoas', Capital: 'Maceió' },
  { id: 'AP', estado: 'Amapá', Capital: 'Macapá' },
  { id: 'AM', estado: 'Amazonas', Capital: 'Manaus' },
  { id: 'BA', estado: 'Bahia', Capital: 'Salvador' },
  { id: 'CE', estado: 'Ceara', Capital: 'Fortaleza' },
  { id: 'DF', estado: 'Distrito Federal', Capital: 'Brasília' },
  { id: 'ES', estado: 'Espírito Santo', Capital: 'Vitória' },
  { id: 'GO', estado: 'Goiás', Capital: 'Goiânia' },
  { id: 'MA', estado: 'Maranhão', Capital: 'São Luiz' },
  { id: 'MT', estado: 'Mato Grosso', Capital: 'Cuiabá' },
  { id: 'MS', estado: 'Mato Grosso do Sul', Capital: 'Campo Grande' },
  { id: 'MG', estado: 'Minas Gerais', Capital: 'Belo Horizonte' },
  { id: 'PA', estado: 'Pará', Capital: 'Belém' },
  { id: 'PB', estado: 'Paraíba', Capital: 'João Pessoa' },
  { id: 'PR', estado: 'Paraná', Capital: 'Curitiba' },
  { id: 'PE', estado: 'Pernambuco', Capital: 'Recife' },
  { id: 'PI', estado: 'Piauí', Capital: 'Terezina' },
  { id: 'RJ', estado: 'Rio de Janeiro', Capital: 'Rio de Janeiro' },
  { id: 'RN', estado: 'Rio Grande do Norte', Capital: 'Natal' },
  { id: 'RS', estado: 'Rio Grande do Sul', Capital: 'Porto Alegre' },
  { id: 'RO', estado: 'Rondônia', Capital: 'Porto Velho' },
  { id: 'RR', estado: 'Roraima', Capital: 'Boa Vista' },
  { id: 'SC', estado: 'Santa Catarina', Capital: 'Florianópolis' },
  { id: 'SP', estado: 'São Paulo', Capital: 'São Paulo' },
  { id: 'SE', estado: 'Sergipe', Capital: 'Aracajú' },
  { id: 'TO', estado: 'Tocantins', Capital: 'Palmas' },
]

export default estato;